name: Node.js CI
on:
  push:
    branches: [test]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install npm deps
        run: npm install
      - name: Run build
        run: npm run build --if-present
      - run: npm ci
