name: Node.js CI
on:
  push:
    branches: [test]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install npm deps
        run: npm install
      - name: Run build
        run: npm run build --if-present
      - run: npm ci  
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
      - run: echo ${{secret.REMOTE_USER}}
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      ARGS: "-rltgoDzv0 --delete"
      SOURCE: "dist/"
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      EXCLUDE: "/dist/, /node/modules"

